version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=devopsroles
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
